services:
  gotify2matrix:
    image: ghcr.io/andretiagogr/gotify2matrix:latest
    container_name: gotify2matrix
    restart: unless-stopped
    env_file:
      - .g2m.env
    volumes:
      - ./session:/session
